# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginScreen(object):
    def setupUi(self, loginScreen):
        loginScreen.setObjectName("loginScreen")
        loginScreen.resize(300, 143)
        self.txtUsername = QtWidgets.QLineEdit(loginScreen)
        self.txtUsername.setGeometry(QtCore.QRect(20, 20, 265, 25))
        self.txtUsername.setText("")
        self.txtUsername.setObjectName("txtUsername")
        self.txtPassword = QtWidgets.QLineEdit(loginScreen)
        self.txtPassword.setGeometry(QtCore.QRect(20, 60, 265, 25))
        self.txtPassword.setText("")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.btnLogin = QtWidgets.QPushButton(loginScreen)
        self.btnLogin.setGeometry(QtCore.QRect(120, 100, 165, 30))
        self.btnLogin.setObjectName("btnLogin")
        self.cbRM = QtWidgets.QCheckBox(loginScreen)
        self.cbRM.setGeometry(QtCore.QRect(20, 105, 90, 20))
        self.cbRM.setObjectName("cbRM")

        self.retranslateUi(loginScreen)
        QtCore.QMetaObject.connectSlotsByName(loginScreen)

    def retranslateUi(self, loginScreen):
        _translate = QtCore.QCoreApplication.translate
        loginScreen.setWindowTitle(_translate("loginScreen", "SNR Margin - Login"))
        self.txtUsername.setPlaceholderText(_translate("loginScreen", "username"))
        self.txtPassword.setPlaceholderText(_translate("loginScreen", "password"))
        self.btnLogin.setText(_translate("loginScreen", "Login"))
        self.cbRM.setText(_translate("loginScreen", "Remember Me"))
