# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainScreen(object):
    def setupUi(self, mainScreen):
        mainScreen.setObjectName("mainScreen")
        mainScreen.resize(421, 173)
        self.horizontalLayoutWidget = QtWidgets.QWidget(mainScreen)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 401, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbVDSL = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.rbVDSL.setChecked(True)
        self.rbVDSL.setObjectName("rbVDSL")
        self.horizontalLayout.addWidget(self.rbVDSL)
        self.rbADSL = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.rbADSL.setObjectName("rbADSL")
        self.horizontalLayout.addWidget(self.rbADSL)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnGet = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnGet.setObjectName("btnGet")
        self.horizontalLayout.addWidget(self.btnGet)
        self.gridLayoutWidget = QtWidgets.QWidget(mainScreen)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 401, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblSNR = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSNR.setObjectName("lblSNR")
        self.gridLayout.addWidget(self.lblSNR, 0, 0, 1, 1)
        self.rbCustom = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rbCustom.setObjectName("rbCustom")
        self.gridLayout.addWidget(self.rbCustom, 1, 3, 1, 1)
        self.lblMode = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblMode.setObjectName("lblMode")
        self.gridLayout.addWidget(self.lblMode, 1, 0, 1, 1)
        self.rbBrowsing = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rbBrowsing.setObjectName("rbBrowsing")
        self.gridLayout.addWidget(self.rbBrowsing, 1, 2, 1, 1)
        self.rbDownload = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rbDownload.setObjectName("rbDownload")
        self.gridLayout.addWidget(self.rbDownload, 1, 1, 1, 1)
        self.lblCustom = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblCustom.setObjectName("lblCustom")
        self.gridLayout.addWidget(self.lblCustom, 2, 0, 1, 1)
        self.txtNewSNR = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtNewSNR.setObjectName("txtNewSNR")
        self.gridLayout.addWidget(self.txtNewSNR, 2, 1, 1, 1)
        self.btnExit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnExit.setObjectName("btnExit")
        self.gridLayout.addWidget(self.btnExit, 2, 2, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 2, 3, 1, 1)
        self.txtSNR = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtSNR.setReadOnly(True)
        self.txtSNR.setObjectName("txtSNR")
        self.gridLayout.addWidget(self.txtSNR, 0, 1, 1, 1)

        self.retranslateUi(mainScreen)
        QtCore.QMetaObject.connectSlotsByName(mainScreen)

    def retranslateUi(self, mainScreen):
        _translate = QtCore.QCoreApplication.translate
        mainScreen.setWindowTitle(_translate("mainScreen", "SNR Margin - Main Screen"))
        self.rbVDSL.setText(_translate("mainScreen", "VDSL"))
        self.rbADSL.setText(_translate("mainScreen", "ADSL"))
        self.btnGet.setText(_translate("mainScreen", "Get SNR Margin"))
        self.lblSNR.setText(_translate("mainScreen", "SNR Margin (dB)"))
        self.rbCustom.setText(_translate("mainScreen", "Custom Mode"))
        self.lblMode.setText(_translate("mainScreen", "Mode"))
        self.rbBrowsing.setText(_translate("mainScreen", "Browsing Mode"))
        self.rbDownload.setText(_translate("mainScreen", "Download Mode"))
        self.lblCustom.setText(_translate("mainScreen", "Custom"))
        self.txtNewSNR.setPlaceholderText(_translate("mainScreen", "dB Value"))
        self.btnExit.setText(_translate("mainScreen", "Exit"))
        self.btnSave.setText(_translate("mainScreen", "Save"))
